pipelines:
  - name: my_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: together
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: chakilams3/for-jfrog-pipelines  # replace with your image path and name
          dockerImageTag: latest
          inputResources:
            - name: github
          integrations:
            - name: newdockerhub    # replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: together
          targetRepository: chakilams3/for-jfrog-pipelines
          integrations:
            - name: newdockerhub    # replace with your artifactory integration
          inputSteps:
            - name: docker_build
