pipelines:
  - name: my_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: together
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: chakilams3/for-jfrog-pipelines  # replace with your image path and name
          dockerImageTag: latest
          inputResources:
            - name: github
          integrations:
            - name: newdockerhub    # replace with your artifactory integration
      - name: push
        type: Bash
        configuration: 
          affinityGroup: together
          inputSteps: 
            - name: docker_build
          execution: 
            onStart:
              - docker login -u chakilams3 -p Santhu@439
            onExecute: 
               - docker image push chakilams3/for-jfrog-pipelines:latest
