pipelines:
  - name: my_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: together
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: cloudnativesol.jfrog.io/artifactorydockerrepo/myfirstimage  # replace with your image path and name
          dockerImageTag: latest
          inputResources:
            - name: github
          integrations:
            - name: artifactorydockerrepo    # replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: together
          targetRepository: example-repo-local
          integrations:
            - name: artifactorydockerrepo    # replace with your artifactory integration
          inputSteps:
            - name: docker_build

      - name: docker_deploy
        type: Bash
        configuration: 
          affinityGroup: together
          inputResources: 
            - name: sshkey
          inputSteps: 
            - name: docker_push
        execution: 
          onStart:
            - docker login cloudnativesol.jfrog.io -u cloudnativesol@gmail.com -p Santhu@439
          onExecute: 
             - ssh -i ~/.ssh/sshkey root@15.206.19.95 "docker image pull cloudnativesol.jfrog.io/artifactorydockerrepo/myfirstimage:latest && docker stop webapp && docker rm webapp && docker rmi cloudnativesol.jfrog.io/artifactorydockerrepo/myfirstimage:current && docker image tag cloudnativesol.jfrog.io/artifactorydockerrepo/myfirstimage:latest cloudnativesol.jfrog.io/artifactorydockerrepo/myfirstimage:current && docker run -d --name webapp -p 8080:80 cloudnativesol.jfrog.io/artifactorydockerrepo/myfirstimage:current"
