pipelines:
  - name: my_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: chakilams3/for-jfrog-pipelines  # replace with your image path and name
          dockerImageTag: latest
          inputResources:
            - name: dockerhub
          integrations:
            - name: dockerhub    # replace with your artifactory integration

  - name: docker_push
    type: DockerPush
    configuration:
      targetRepository: example-repo-local
      integrations:
        - name: jfrog_artifactory_int    # replace with your artifactory integration
      inputSteps:
        - name: docker_build
      outputResources:
        - name: dbp_image
